server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
    mail:
      host: smtp.sina.com
      username: imcaidoge@sina.com
      password: 53244ce859f5d93f
      protocol: smtps
      properties:
        auth: true
        port: 465 #465或者994
        starttls:
          enable: true
          required: true
        ssl:
          enable: true
# 下面是自定义配置
# 作者信息
author:
  name: 子墨
  url: https://blog.zimo.wiki
  email: 461009747@qq.com
# api信息
api-info:
  title: 模拟登陆金智教务系统统一登陆获取登录后cookies的API——Java
  version: 1.0
  description: "<h3>处理流程</h3><p>接收请求参数-&gt;模拟请求对应教务系统，获取It等需要提交的表单信息-&gt;检查是否需要验证码-&gt;识别验证码-&gt;发起登陆请求-&gt;获取登陆后的cookies</p><h3>二次开发时需要注意金智的反爬策略</h3><ol><li>一个页面一个cookie</li><li>部分教务系统对密码字段做了aes加密</li><li>部分教务系统做了前端加密，如电子科大</li></ol>"
# 默认宜宾学院教务系统的地址
# 登陆页同时也是登陆接口
LOGIN_API: https://authserver-443.webvpn.jxust.edu.cn/authserver/login?service=https%3A%2F%2Fwebvpn.jxust.edu.cn%2Fusers%2Fauth%2Fcas%2Fcallback%3Furl
sjmsValue: 9477CC7DA571A58DE0531F0210ACABF2
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理
    #表单项类型，对应今日校园接口返回的fieldType字段，1代表文本，2代表单选，3代表多选，4代表图片
    - type: 2
      #表单项标题
      title: 是否在江西省内？
      #表单项默认值
      value: 是
    - type: 2
      title: 今天是否在学校？
      value: 是
    - type: 2
      title: 近14天是否接触过新冠肺炎确诊病例、疑似病例、无症状感染者？
      value: 否
    - type: 2
      title: 近14天内是否途径、逗留中高风险地区？（以县区所在地为认定范围）
      value: 否
    - type: 3
      title: 今天是否有发热、咳嗽、呼吸困难等症状？
      value: 没有以上症状
    - type: 1
      title: 今天的体温多少？
      value: 36.2